### PR TITLE
Adds composer.json

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by daim2k5** [comment]
:+1:

**Comment by cmckni3** [comment]
@daim2k5 Does the composer.json look correct? I'm not used to creating composer packages. I haven't really done PHP development in a few years. I have mostly been doing node, ruby, and iOS development.

**Comment by daim2k5** [comment]
yes the composer.json is valid

**Comment by r8** [comment]
Thanks

**Comment by cmckni3** [comment]
No problem

**Pull request merged**
